version: '3'

services:
  core-api:
    image: 'node:8.12.0-alpine'
    working_dir: '/home/core-api'
    volumes:
      - ./:/home/core-api
    command: "sh -c 'npm install && npm run dev'"
    depends_on:
      - core-db
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  core-db:
    image: 'mongo:4'